var levelData=[
	{
		title:"So simple",
		data:[
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:4,l:false},{n:1,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:4,l:false},{n:2,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:1,l:false},{n:3,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:3,l:false},{n:3,l:false},{n:4,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:5,l:true},{n:5,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
		]
	},
	{
		title:"Might have to think a little",
		data:[
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:5,l:false},{n:4,l:false},{n:5,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:5,l:false},{n:3,l:false},{n:2,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:3,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:5,l:false},{n:3,l:false},{n:4,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:6,l:true},{n:5,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
		]
	},
	{
		title:"What's happening?",
		data:[
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:5,l:false},{n:4,l:false},{n:6,l:true},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:4,l:false},{n:2,l:false},{n:2,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:1,l:false},{n:5,l:false},{n:3,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:4,l:false},{n:3,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:5,l:false},{n:3,l:false},{n:4,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:6,l:true},{n:5,l:false},{n:5,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
		]
	},
	{
		title:"Who keeps doing this?",
		data:[
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:3,l:false},{n:4,l:false},{n:5,l:true},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:4,l:false},{n:2,l:false},{n:2,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:5,l:false},{n:3,l:false},{n:3,l:false},{n:0,l:false},
			{n:0,l:false},{n:4,l:false},{n:4,l:false},{n:2,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:5,l:false},{n:3,l:false},{n:4,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:2,l:true},{n:5,l:false},{n:2,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
		]
	},
	{
		title:"Probably can't be solved",
		data:[
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
			{n:0,l:false},{n:3,l:false},{n:6,l:false},{n:5,l:true},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:2,l:false},{n:2,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:5,l:false},{n:5,l:false},{n:3,l:false},{n:0,l:false},
			{n:0,l:false},{n:4,l:false},{n:4,l:false},{n:4,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:2,l:false},{n:1,l:false},{n:1,l:false},{n:1,l:false},{n:0,l:false},
			{n:0,l:false},{n:5,l:false},{n:3,l:false},{n:4,l:false},{n:4,l:false},{n:0,l:false},
			{n:0,l:false},{n:1,l:false},{n:2,l:true},{n:5,l:false},{n:2,l:false},{n:0,l:false},
			{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},{n:0,l:false},
		]
	}
];